controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    paletizador_controller:
      type: joint_trajectory_controller/JointTrajectoryController

paletizador_controller:
  ros__parameters:
    joints:
      - "eje_x"
      - "eje_y"
      - "eje_z"
      - "muneca"
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    # Las ganancias van dentro de ros__parameters
    gains:
      eje_x:
        p: 1000.0
        i: 10.0
        d: 50.0
      eje_y:
        p: 1000.0
        i: 10.0
        d: 50.0
      eje_z:
        p: 20000.0  
        i: 1000.0   
        d: 500.0    
      muneca:
        p: 5000.0
        i: 50.0
        d: 10.0